services:
  - type: web
    plan: free
    name: MusicBot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    repo: https://github.com/MyLoveMoon/DMusicRender
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER_ID
        sync: false
      - key: MONGO_DB_URI
        sync: false
      - key: LOG_GROUP_ID
        sync: false
      - key: START_IMG_URL
        sync: false
      - key: UPSTREAM_REPO
        sync: false
      - key: STRING_SESSION
        sync: false

        
